#!/bin/bash

numero_secreto=$(($RANDOM % 100 + 1))
intentos=0

echo "Adivina el número (entre 1 y 100)"

while true; do
read -p "Introduce tu intento: " intento 
((intentos++))

if((intento == numero_secreto)); then
echo "¡Correcto! Adivinaste en $intentos intentos."
elif((intento < numero_secreto)); then
echo "Demasiado bajo. Intenta de nuevo"
else
echo "Demasiado alto. Intenta de nuevo."
fi
done
